# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - policy_vars.yml
  tasks:
    - name: Modify Groups
      nsxt_policy_group:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        state: "{{ security_group.state }}"
        validate_certs: "{{ validate_certs }}"
        domain_id: "{{ item.domain_id }}"
        display_name: "{{ item.display_name }}"
        expression: "{{ item.expression }}"
        #tags: "{{ tags }}"
      with_items:
        - "{{ mygroups }}"
